services:
  
  # Development SMTP server with webmail
  # Email interface accessible via http://localhost:8025
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      # Set to port 25 replaces local sendmail (and avoid spamming people)
      # You can override these variables in .env
      - ${MAILHOG_SMTP_PORT:-25}:1025
      - ${MAILHOG_HTTP_PORT:-8025}:8025
    networks:
      customnetwork:
        ipv4_address: 192.168.133.3

## Optional services
## Use --profile to launch

# Full-text search solr 8 server
# version 8 is the latest supported by Drupal
# see https://www.drupal.org/project/search_api_solr
  solr8:
    image: library/solr:8
    container_name: solr8
    restart: unless-stopped
    profiles:
      - all
      - drupal
      - solr
    volumes:
      - solr8-cores:/var/solr
    ports:
      # You can override this variable in .env
      - ${SOLR8_HTTP_PORT:-8983}:8983
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx3g"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      customnetwork:
        ipv4_address: 192.168.133.5

  # MariaDB SQL server
  mariadb:
    image: library/mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    profiles:
      - all
      - drupal
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
      TZ: Europe/Bucharest
    ports:
      # You can override this variable in .env
      - ${MARIADB_PORT:-3306}:3306
    #tmpfs:
    #  - /var/lib/mysql
    volumes:
      - ./conf/mariadb/passwd:/root/.my.cnf
      - ./conf/mariadb/drupal.cnf:/etc/mysql/conf.d/90-drupal.cnf
      - ./data/mariadb/init:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
      # -  ramdisk:/var/lib/mysql:rw
    networks:
      customnetwork:
        ipv4_address: 192.168.133.8

  # Apache Tomcat 7 server
  # For Java web apps
  tomcat7:
    image: tomcat:7-jre8
    container_name: tomcat7
    profiles:
      - all
      - tomcat
    ports:
      # You can override this variable in .env
      - ${TOMCAT7_PORT:-8080}:8080
    networks:
      customnetwork:
        ipv4_address: 192.168.133.6

  redis:
    image: redis:8.0-M01
    container_name: redis
    restart: unless-stopped
    profiles:
      - all
      - drupal
      - varnish
    volumes:
      - redis-cache:/data
      - ./conf/redis/redis.conf:/usr/local/redis.conf
    entrypoint: redis-server /usr/local/redis.conf
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      customnetwork:
        ipv4_address: 192.168.133.9

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    restart: unless-stopped
    profiles:
      - all
      - drupal
      - varnish
    command:
      - --conn-limit=1024
      - --memory-limit=512
      - --threads=4
    ports:
      - ${REDIS_PORT:-11211}:11211
    networks:
      customnetwork:
        ipv4_address: 192.168.133.10

  # Varnish server
  varnish:
    image: varnish:7
    container_name: varnish
    restart: unless-stopped
    profiles:
      - all
      - drupal
      - varnish
    volumes:
      - ./conf/varnish/secret:/etc/varnish/secret
      - ./conf/varnish/varnish.params:/etc/varnish/varnish.params
      - ./conf/varnish/drupal.vcl:/etc/varnish/default.vcl
    environment:
      VARNISHD_PARAMS: "-p http_max_hdr=512 -p http_resp_hdr_len=1024768 -p http_resp_size=3024768 -p thread_pool_min=200 -p thread_pool_max=500 -p http_req_size=64000"
    ports:
      # You can override this variable in .env
      - ${VARNISH_PORT:-6081}:80
      # Management port
      # - "0.0.0.0:6082:6082"
    networks:
      customnetwork:
        ipv4_address: 192.168.133.7

volumes:
  solr8-cores:
  mariadb-data:
  redis-cache:
# ramdisk:
#   driver_opts:
#     type: tmpfs
#     device: tmpfs

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 192.168.133.0/24
