version: '3.3'

services:


# Email service and webmail

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 25:1025
      - 8025:8025

# Apache Solr servers

#  solr6:
#    image: library/solr:6
#    container_name: solr6
#    restart: unless-stopped
#    volumes:
#      - ./solr/6/cores:/opt/solr/server/solr/cores
#      - ./solr/6/home:/home/solr
#    ports:
#      - 8984:8983

  solr7:
    image: library/solr:7
    container_name: solr7
    restart: unless-stopped
    volumes:
      - ./solr/7/cores:/opt/solr/server/solr/cores
      - ./solr/7/home:/home/solr
    ports:
      - 0.0.0.0:8983:8983

  solr8:
    image: library/solr:8.5.2
    container_name: solr8
    restart: unless-stopped
    volumes:
      - ./solr/8/cores:/var/solr/data
    ports:
      - 8985:8983

# Tomcat servers

#  tomcat7:
#    image: tomcat:7-jre8
#    container_name: tomcat7
#    container_name: host.tomcat7
#    volumes:
##       - ./tomcat7-webapps:/usr/local/tomcat/webapps
### eHolcim specific
##       - /home/cristiroma/Work/holcim/pdf-service/target/pdf-service.war:/usr/local/tomcat/webapps/pdf-service.war
##       - /home/cristiroma/Work/holcim/pdf-service/util/mysql-connector-java-5.1.29-bin.jar:/usr/local/tomcat/lib/mysql-connector-java-5.1.29-bin.jar
##       - /home/cristiroma/Work/holcim/eholcim/web/sites/default/files/private/cert-trusted:/eholcim-cert-trusted
##       - /home/cristiroma/Work/holcim/eholcim/web/sites/default/files/private/secure-store/cert-new:/eholcim-secure-store-cert-new
##       - /home/cristiroma/Work/holcim/eholcim/web/sites/default/files/private/secure-store/temp:/eholcim-secure-store-temp
##       - /home/cristiroma/Work/holcim/eholcim/web/sites/default/files/private/pdf-templates:/eholcim-pdf-templates
#     ports:
#       - "0.0.0.0:8888:8080"

# Varnish
 
#  varnish:
#    image: million12/varnish
#    volumes:
#       - ./varnish/secret:/etc/varnish/secret
#       - ./varnish/drupal8.vcl:/etc/varnish/default.vcl

# SQL servers

#  mariadb:
#    image: library/mariadb:10.5
#    container_name: mariadb
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      TZ: Europe/Bucharest
#    ports:
#      - 3307:3306
#    tmpfs:
#      - /var/lib/mysql
#    volumes:
#      - ./mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
#      - ./mariadb/my.cnf:/etc/mysql/my.cnf
#      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
## IMPORTANT! Store the MySQL data in RAM drive for fastes performance. 
## All data is lost after container is restarted
## Uncomment volumes at the end of the file
##      -  ramdisk:/var/lib/mysql:rw


#volumes:
#  ramdisk:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs